version: "3.9"

services:
  frontend-service:
    build: ./frontend-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend-service

  backend-service:
    build: ./backend-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres-service
      - redis-service

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - postgres-service

  payments-service:
    build: ./payments-service
    ports:
      - "8002:3000"
    env_file:
      - .env
    depends_on:
      - rabbitmq-service

  worker-service:
    build: ./worker-service
    env_file:
      - .env
    depends_on:
      - rabbitmq-service
      - redis-service

  postgres-service:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-service:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq-service:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  adminer-service:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres-service

volumes:
  postgres_data:

